#! /bin/sh

# if pgrep firewall-applet &> /dev/null;then pkill firewall-applet;fi &

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor eDP1 -d I II III IV V VI

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# get vm_class:  xprop | grep VM_CLASS
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a obsidian desktop='^3' follow=on
bspc rule -a yesplaymusic desktop='^6' follow=on
bspc rule -a Yad state=floating
bspc rule -a flameshot state=floating sticky=on
bspc rule -a xfce4-power-manager state=floating
bspc rule -a copyq state=floating center=on
bspc rule -a GoldenDict state=floating sticky=on center=on
bspc rule -a Imagine state=floating center=on
bspc rule -a Xfce4-terminal state=floating rectangle=900x600+0+0 center=on

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &
# Bar
flameshot &
# xfce4-power-manager &
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ & 
# Picom
picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# Set up a desktop where all windows are floating
~/.config/bspwm/scripts/bspwm-desktop-floating.sh &
